local C = require "ui.theme.colors"

return {
    DapBreakpoint = { fg = C.color1, bold = true },
    DapUIVariable = { link = "@variable" },
    DapUIScope = { fg = C.color6, bold = true },
    DapUIType = { link = "@type" },
    DapUIModifiedValue = { fg = C.color1, bold = true },
    DapUIDecoration = C.hint,
    DapUISource = { fg = C.color5 },
    DapUILineNumber = { link = "LineNr" },
    DapUIWatchesEmpty = { fg = C.color1, bold = true },
    DapUIWatchesValue = C.color2,
    DapUIWatchesError = { link = "Error" },
    DapUIBreakpointsPath = C.color4,
    DapUIBreakpointsCurrentLine = { fg = C.color4, bg = C.selection, bold = true },
    DapUIBreakpointsDisabledLine = { fg = C.comment },
    DapUIStepOver = C.color6,
    DapUIStepInto = C.color6,
    DapUIStepOut = C.color3,
    DapUIStepBack = C.color6,
    DapUIStop = C.color1,
    DapUIPlayPause = C.color2,
    DapUIRestart = C.color2,
    DapUIUnavailable = C.comment,
    DapUIStepOverNC = C.color6,
    DapUIStepIntoNC = C.color6,
    DapUIStepOutNC = C.color3,
    DapUIStepBackNC = C.color6,
    DapUIStopNC = C.color1,
    DapUIPlayPauseNC = C.color2,
    DapUIRestartNC = C.color2,
    DapUIUnavailableNC = C.comment,
    DapUIWinbarSymbol = C.color5,
}
