local C = require "ui.theme.colors"

return {
    NavicIconsArray = { bg = C.light_background, fg = C.color1 },
    NavicIconsBoolean = { bg = C.light_background, fg = C.color11 },
    NavicIconsClass = { bg = C.light_background, fg = C.color3 },
    NavicIconsConstant = { bg = C.light_background, fg = C.color3 },
    NavicIconsConstructor = { bg = C.light_background, fg = C.color4 },
    NavicIconsEnum = { bg = C.light_background, fg = C.color3 },
    NavicIconsEnumEmeber = { bg = C.light_background, fg = C.color4 },
    NavicIconsEvent = { bg = C.light_background, fg = C.color1 },
    NavicIconsField = { bg = C.light_background, fg = C.color4 },
    NavicIconsFile = { bg = C.light_background, fg = C.color4 },
    NavicIconsFunction = { bg = C.light_background, fg = C.color4 },
    NavicIconsInterface = { bg = C.light_background, fg = C.color3 },
    NavicIconsKey = { bg = C.light_background, fg = C.color4 },
    NavicIconsMethod = { bg = C.light_background, fg = C.color4 },
    NavicIconsModule = { bg = C.light_background, fg = C.color1 },
    NavicIconsNamespace = { bg = C.light_background, fg = C.color1 },
    NavicIconsNull = { bg = C.light_background, fg = C.comment },
    NavicIconsNumber = { bg = C.light_background, fg = C.color3 },
    NavicIconsObject = { bg = C.light_background, fg = C.color1 },
    NavicIconsOperator = { bg = C.light_background, fg = C.color7 },
    NavicIconsPackage = { bg = C.light_background, fg = C.color3 },
    NavicIconsProperty = { bg = C.light_background, fg = C.color4 },
    NavicIconsString = { bg = C.light_background, fg = C.color2 },
    NavicIconsStruct = { bg = C.light_background, fg = C.color3 },
    NavicIconsTypeParameter = { bg = C.light_background, fg = C.color11 },
    NavicIconsVariable = { bg = C.light_background, fg = C.color6 },
    NavicSeparator = { bg = C.light_background, fg = C.comment },
    NavicText = { bg = C.light_background, fg = C.foreground },
}
