local C = require "ui.theme.colors"

return {
    NavicIconsArray = C.color1,
    NavicIconsBoolean = C.color11,
    NavicIconsClass = C.color3,
    NavicIconsConstant = C.color3,
    NavicIconsConstructor = C.color4,
    NavicIconsEnum = C.color3,
    NavicIconsEnumEmeber = C.color4,
    NavicIconsEvent = C.color1,
    NavicIconsField = C.color4,
    NavicIconsFile = C.color4,
    NavicIconsFunction = C.color4,
    NavicIconsInterface = C.color3,
    NavicIconsKey = C.color4,
    NavicIconsMethod = C.color4,
    NavicIconsModule = C.color1,
    NavicIconsNamespace = C.color1,
    NavicIconsNull = C.comment,
    NavicIconsNumber = C.color3,
    NavicIconsObject = C.color1,
    NavicIconsOperator = C.color7,
    NavicIconsPackage = C.color3,
    NavicIconsProperty = C.color4,
    NavicIconsString = C.color2,
    NavicIconsStruct = C.color3,
    NavicIconsTypeParameter = C.color11,
    NavicIconsVariable = C.color6,
    NavicSeparator = C.comment,
    NavicText = C.foreground,
}
