local C = require "ui.theme.colors"

return {
    ["@boolean"] = C.color3,
    ["@character"] = { fg = C.color1, bold = true },
    ["@character.special"] = C.color6,
    ["@comment"] = { fg = C.comment, italic = true },
    ["@conditional"] = C.color5,
    ["@constant"] = { fg = C.color3, italic = true },
    ["@constant.builtin"] = C.color3,
    ["@constant.macro"] = C.color1,
    ["@constructor"] = C.color1,
    ["@debug"] = C.color1,
    ["@define"] = C.color5,
    ["@exception"] = { link = "Exception" },
    ["@field"] = C.foreground,
    ["@float"] = { link = "Float" },
    ["@function"] = C.color4,
    ["@function.builtin"] = C.color4,
    ["@function.macro"] = C.color1,
    ["@include"] = { link = "Include" },
    ["@keyword"] = { fg = C.color5, italic = true },
    ["@label"] = C.color3,
    ["@macro"] = C.color1,
    ["@method"] = { link = "@function" },
    ["@namespace"] = C.color1,
    ["@number"] = C.color3,
    ["@operator"] = C.color7,
    ["@parameter"] = { fg = C.foreground, italic = true },
    ["@preproc"] = C.color3,
    ["@property"] = C.foreground,
    ["@punctuation"] = C.color1,
    ["@repeat"] = { fg = C.color3, italic = true },
    ["@storageclass"] = { fg = C.color3, italic = true },
    ["@string"] = C.color2,
    ["@string.escape"] = C.color4,
    ["@string.special"] = { fg = C.color6, bold = true },
    ["@tag"] = C.color3,
    ["@text.title"] = C.color6,
    ["@text.todo"] = C.color4,
    ["@text.reference"] = C.color5,
    ["@text.uri"] = C.color4,
    ["@type"] = { fg = C.color11, italic = true },
    ["@type.definition"] = { link = "@type" },
    ["@variable"] = C.foreground,
}
